cupertino_icons: ^1.0.2
  get: 4.3.8
  auto_size_text: ^3.0.0-nullsafety.0
  pin_input_text_field: ^4.1.1
  flutter_feather_icons: ^2.0.0+1
  get_storage: ^2.0.3
  dio: ^4.0.0
  http: ^0.13.3
  carousel_slider: ^4.0.0
  extended_sliver: ^2.0.1
  flutter_cart: ^0.0.6
  google_maps_place_picker:
    git:
      url: https://github.com/iamirzashowvik/google-map-picker-
  #^2.1.0-nullsafety.3
  url_launcher: ^6.0.12
  fcm_config: ^3.1.8 #//todo android done :ios baki
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_inappwebview: ^5.3.2
  flutter_easyloading: ^3.0.3
  loading_indicator: ^3.0.2
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  device_info_plus: ^3.1.0
  introduction_screen: ^2.1.0
  flutter_svg: ^0.23.0+1
  scrollable_positioned_list: ^0.2.2
  package_info_plus: ^1.3.0
  firebase_core: ^1.10.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/intro/
    - assets/order-tracking/

  fonts:
    - family: Sk-Modernist
      fonts:
        - asset: assets/fonts/Sk-Modernist-Regular.ttf
          style: normal
    - family: Gordita-Regular
      fonts:
        - asset: assets/fonts/Gordita/Gordita-Regular.otf
    - family: Gordita-Medium
      fonts:
        - asset: assets/fonts/Gordita/Gordita-Medium.otf
    - family: Gordita-Bold
      fonts:
        - asset: assets/fonts/Gordita/Gordita-Bold.otf
